# ==============================================================================
# Config.yml
# ------------------------------------------------------------------------------
#
# This is the main configuration file for the website. The 'theme' value should
# match the name of the folder in /themes that contains your theme files; if
# you've copied the default theme and given it a different name make sure to
# update the value here too.

# Use these settings for serving/building to a path other than root
# baseurl: "https://gettypubs.github.io/keepitmoving"
# canonifyURLs: true

# Use these settings for serving/building to the root path
baseurl: ""
relativeURLs: true

theme: "quire-base-theme"
footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"

blackfriday:
  fractions: false

# These values can be accessed in templates via .Site.Params
params:
  searchEnabled: true
  imageLabelContentBefore: "Figure "
  imageLabelContentAfter: ". "
  displayBiblioShort: "true"
  tocType: "full"
  menuType:  "short"
  citationPageLocationDivider: ":"

